import dive from './dive'
import homePage from './homePage'
import privacyPolicy from './privacyPolicy'
import recruitmentPolicy from './recruitmentPolicy'
import certifications from './certifications'
import certification from './certification'
import aboutUs from './aboutUs'
import divelogsOverview from './divelogsOverview'
import activitiesOverview from './activitiesOverview'
import activity from './activity'
import membershipPage from './membershipPage'
import contactPage from './contactPage'
import youtubeEmbed from './youtubeEmbed'

export const schemaTypes = [homePage, aboutUs, membershipPage, contactPage, certifications, certification, divelogsOverview, activitiesOverview, dive, activity, privacyPolicy, recruitmentPolicy, youtubeEmbed]
